# Generated by Django 4.0.4 on 2022-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('greeting_1', models.CharField(max_length=5)),
                ('greeting_2', models.CharField(max_length=5)),
                ('picture', models.ImageField(upload_to='picture/')),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
